language: java
notifications:
  hipchat:
    rooms:
      secure: D2+NwvMr+nuEiZcZOVTjTdVhWzPbOnpMEuyjr3yLwp5pgpJSZx3gUfYPb/xiBWzcKdGRRZbXVCHq5IVtF1w7g99x+F8F15V5cRLQidZLJZbHxaAWPjOfmcBrYDw/vB32XqVn5h+ry7G5BOH8+VB5/2ZHCQkLOSMe+RpgTPEy2DYtjci+cfe90onurD4UdzGBi2RAV/uRlwx7khrEEs8p5EX8Dlq142Sd1PhKKl/AudqUlcgBYkXSV9V+n7c4vgQHaL/6Y1/h//LGxSlYjHsiHsaFs+2GHCSj6sVz3s6vsFzbFIbHNn88mgRPTiUgMokL/Os5eyjp2bQ947jMDRyi9DvRdoZ782kmLClW4IJ6Qu/FCAW0fygrY+X6o2IwKFkliw4e80QzXx97nFke2wYyj62FoyDEhSGdy+TJBX0KS9jcB9tIeYspv7uGkJobshRqWNm10tPSaubVRMx8IvVeJO4WBccHZvp8MHPGDkV8g1JyTpifwLvwPsKN56qvguERFc30TYxwT0oKMwEQPcuH6evtgdr9vXOSf0l8VrerycjsLiCYqcLQ886w4RaOthI30fiN3J/Ya/jGBt8Ywl9TlxLyFi24OAQaG6M8gOHHAQRPbHDFkGDDgsXLxL68HPYcufd6JQOtE2aKc2dzooIZadNEwGxGNcmfwlMmzaul5TY=
deploy:
  provider: releases
  api_key:
    secure: hLA9u/rQfVT1h1pOxjbZxqlgg0Qr4kHFEdpcy+lr4PBPvwgbk1yzN+a562FEItJ8q8POfCgkZ7NF7J2M4Vw/XkiUK18h8aca84iVFztqiYWm/voGp4P4W/5XbJDSs5p1rfvv9FyfMKOEvJR/1RnscbVC2dfAzlyaKGwVqgbejvIN54wVjPVAgss9tmh5x+x2Okt1JGAN+TXxlaDnIFtEhRyAXJToc1zwAF4+L11Q5dKExNpGNJRLQ0DZxfUOK43ZJbY8UlOXuANZyA26JoO7en9aGnrsWsdiUuPSl5xXWExhTmsFt3T1B0QfauIMGWNt0svSTDMy2pc8VfkGvuHp7kQpJPo1bOyFoLGhZHUjSBVTr7BtcHXceBsipZQZv0eGFamRLCd1SlepBiTj/3wnWk7aKz+qyaDOLbOg2K/tVlOEDLGO1IT67+wVlMn/bkZm0S7lzu5yOtrO3Q0RoZugkqZaVlAbqe8JvuihPQ+ekRGZq0yt/ZYsc07bDJFSOO99d2ZGcp2TvqnzFSpf2xkXxCopPKrWUAq/5GDwmMTc1crfC0l6KbGIeFvII277h9KA5wM+CHGNJ8OR7f6vF+6AtUY5YQtOTRyNtH5Eio3p51WZCRJBEltE9AGBcmyNrmu0t8ix9jZu7DaO6y6xkd1Eqbi5A4lJV3mVzJvhdAw3ICU=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-datical-plugin
